name = input("Enter your name: ")
age = input("Enter your age: ")
college = input("Enter your college: ")
branch = input("Enter your branch: ")
print("\nStudent Profile")
print("Name:", name)
print("Age:", age)
print("College:", college)
print("Branch:", branch)
